### ISSUE TITLE
Ошибка при обновлении e2e

### ISSUE THREAD

**Issue by ilchukovaolga** [CSSSR/e2e-tools#28]
На проекте отображается ошибка при обновлении через yarn et upgrade.

```
error D:\Работа\gazprom\e2e-tests\node_modules\chromedriver: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: D:\Работа\gazprom\e2e-tests\node_modules\chromedriver
Output:
ChromeDriver binary exists. Validating...
ChromeDriver is already available at 'C:\Users\2BB2~1\AppData\Local\Temp\89.0.4389.23\chromedriver\chromedriver.exe'.
Copying to target path D:\Работа\gazprom\e2e-tests\node_modules\chromedriver\lib\chromedriver
ChromeDriver installation failed Error: EEXIST: file already exists, mkdir 'D:\Работа\gazprom\e2e-tests\node_modules\chromedriver\lib\chromedriver'
    at Object.mkdirSync (fs.js:841:3)
    at copyIntoPlace (D:\Работа\gazprom\e2e-tests\node_modules\chromedriver\install.js:302:6)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async install (D:\Работа\gazprom\e2e-tests\node_modules\chromedriver\install.js:65:5) {
  errno: -4075,
  syscall: 'mkdir',
  code: 'EEXIST',
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @csssr/e2e-tools-nightwatch@1.15.0
info All dependencies
└─ @csssr/e2e-tools-nightwatch@1.15.0
et.js upgrade
Upgrades all packages
Options:
  --version            Show version number                             [boolean]
  --help               Show help                                       [boolean]
  --updatePackageJson  Whether update package versions in package.json on just
                       regenerate files. Useful to for beta versions
                                                       [boolean] [default: true]
SyntaxError: Unexpected token {
    at unexpected (D:\Работа\gazprom\e2e-tests\node_modules\comment-json\src\parse.js:87:17)
    at expect (D:\Работа\gazprom\e2e-tests\node_modules\comment-json\src\parse.js:132:5)
    at parse_array (D:\Работа\gazprom\e2e-tests\node_modules\comment-json\src\parse.js:321:7)
    at walk (D:\Работа\gazprom\e2e-tests\node_modules\comment-json\src\parse.js:370:12)
    at parse_object (D:\Работа\gazprom\e2e-tests\node_modules\comment-json\src\parse.js:283:33)
    at walk (D:\Работа\gazprom\e2e-tests\node_modules\comment-json\src\parse.js:365:12)
    at Object.parse (D:\Работа\gazprom\e2e-tests\node_modules\comment-json\src\parse.js:417:16)
    at updateJsonFile (D:\Работа\gazprom\e2e-tests\node_modules\@csssr\e2e-tools\src\utils\index.js:95:40)
    at updateVsCodeTasks (D:\Работа\gazprom\e2e-tests\node_modules\@csssr\e2e-tools-nightwatch\src\upgrades\vscode-tasks.js:6:3)
    at Object.upgrade (D:\Работа\gazprom\e2e-tests\node_modules\@csssr\e2e-tools-nightwatch\src\index.js:134:3) {
  line: 91,
  column: 4
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn et upgrade" terminated with exit code: 1.
```

**Comment by Nitive** [comment]
Там в конфиге пропущена запятая
![image](https://user-images.githubusercontent.com/6770225/116097873-3c8a8580-a6b3-11eb-8729-abad363978ee.png)
